image:
  repository: crewmeister-challenge
  tag: replace-me

serviceAccount:
  annotations:: {} # THIS NEEDS TO BE ADDED AFTER INFRA IS DEPlOYED

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

config:
  create: true
  name: crewmeister-challenge
  data:
    SPRING_FLYWAY_ENABLED: "true"