apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "crewmeister-challenge.fullname" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ include "crewmeister-challenge.fullname" . }}
    kind: ClusterSecretStore
  target:
    name: {{ include "crewmeister-challenge.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: my-secret-key
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: my-secret-key
        property: password
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: my-secret-key
        property: password
    - secretKey: SPRING_DATASOURCE_WRITER_URL
      remoteRef:
        key: my-secret-key
        property: password
    
