apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "crewmeister-challenge.fullname" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ include "crewmeister-challenge.fullname" . }}
    kind: ClusterSecretStore
  target:
    name: {{ include "crewmeister-challenge.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: my-secret-key #AWS Secrets Manager secret name
        property: username #AWS Secrets Manager secret key
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: my-secret-key
        property: password
    - secretKey: SPRING_DATASOURCE_HOST
      remoteRef:
        key: my-secret-key
        property: host
    - secretKey: SPRING_DATASOURCE_PORT
      remoteRef:
        key: my-secret-key
        property: port
    - secretKey: SPRING_DATASOURCE_DB_NAME
      remoteRef:
        key: my-secret-key
        property: dbname
    
