name: Build and Deploy to EKS

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "terraform/**"

env:
  ECR_REPOSITORY: "crewmesiter/challenge"
  HELM_CHART_PATH: "./helm/crewmeister/crewmeister-challenge" 
  APP_NAME: cm-challenge

ou

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::8} -t $REGISTRY/$ECR_REPOSITORY:latest .
          docker push $REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::8}
          docker push $REGISTRY/$ECR_REPOSITORY:latest 
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV

  deploy:
    name: Deploy Helm Chart to EKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
###
##
# This needs to be tested
##
###
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ env.APP_NAME }} ${{ env.HELM_CHART_PATH }} -f ${{ env.HELM_CHART_PATH}}/values-dev.yaml \
            --set image.repository=${{ env.REGISTRY }}/${{ env.ECR_REPOSITORY }} \
            --set image.tag=image.tag=${{ env.IMAGE_TAG }} \
            --atomic --wait