name: Terraform

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "terraform/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "terraform/**"
env:
  TF_VAR_FILE: "envs/cm-challenge-dev-eu-c1.tfvars"
  TF_DIR: terraform/stacks/crewmeister-challenge
jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
                
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform Format Check
        working-directory: ${{ env.TF_DIR }}
        run: terraform fmt -list=true -write=false -diff=true -check=true -recursive

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform plan -out=plan.cache -var-file=${{ env.TF_VAR_FILE }}
          terraform show --json plan.cache | tee plan.json

      - name: Upload Terraform Plan JSON
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-json
          path: ${{ env.TF_DIR }}/plan.json

      - name: Terraform Apply (Only on Main Branch)
        working-directory: ${{ env.TF_DIR }}
        if: github.ref == 'refs/heads/main'
        run: terraform apply plan.cache
